---
title: "MS-CSI"
description: |
  A scientific project financed by the Association pour la recherche en Sclérose en Plaques (ARSEP) for studying gait impairment in multiple sclerosis using two sources of information, namely MRI data and sensor data.
---

The MS-CSI project aims at exploring the relationships between lesion
load quantified by MRI and the individual gait pattern (IGP) computed by
the eGait device, which is a device jointly developed by the Department
of Mathematics Jean Leray
([LMJL](https://www.math.sciences.univ-nantes.fr)) and the
[UmanIT](https://www.umanit.fr) company in Nantes, France.

# Rationale

In the course of their lifetime, $75\%$ of patients diagnosed with
multiple sclerosis (MS) complain about reduced mobility due to walking
deficiencies. In clinical pratice, gait impairment is evaluated during
the clinical exam using mainly three indicators:

1.  The time required for a patient to walk twice a distance of $25$
    feet; this is the so-called *Timed* $25$ *Foot Walk* (T25FW),
2.  The walking perimeter of a patient, which is a part of the so-called
    EDSS score,
3.  The cerebral and spinal lesion load, quantified by means of MR
    imaging.

These indicators however do not disentangle the various underlying forms
of walking disabilities such as motor impairment, spacticity,
equilibrium and so on.

The advent and development of connected devices offer a unique
opportunity to collect non-invasive quantitative (and thus objective)
data about a patient's health, at minimal cost. The UmanIT company
together with the Department of Mathematics Jean Leray (LMJL) have
developed a medical device coined *eGait* paired with a statistical
method that generates an individual gait pattern (IGP) using data
collected by a motion sensor. The IGP represents the evolution of hip
rotation during a typical walking cycle. The IGP represents an objective
biomarker of gait impairment that is easily computed from data collected
non-invasively and at minimal cost. The scientific hypothesis is that
the IGP should share common information about gait impairment be
competitive with other

# Specific Aims

We focus in this project on the assessment of gait impairment. The
original contributions are:

-   to propose a non-invasive low-cost medical device that generates an
    individual gait pattern for the patient during his/her clinical
    exam,
-   to study the statistical associations between the provided IGP and
    the lesion load obtained from the MRI data.

The project is build on mainly three specific aims:

Specific Aim 1

:   To evaluate the statistical associations between the IGP obtained
    from the sensor data and the lesion load obtained from the MRI data.

Specific Aim 2

:   To find group-level gait patterns using external sources of
    information such as lesion load provided by the MRI data or overall
    disability score provided by the EDSS data.

Specific Aim 3

:   To explain and predict the lesion load specific to a neuronal
    pathway or the membership to the previously determined groups, using
    the IGPs.

# Methodology

Patients from the [OFSEP-HD](https://www.ofsep.org/fr/cohorte-hd) cohort
that are seen in the University Hospital either in Nantes or Rennes will
be wearing the eGait device during their T25FW test for obtaining their
individual gait pattern (we predict $100$ inclusions). As part of the
standard protocol of this cohort, a number of demographic and clinical
data will be collected as well. In addition, specific cutting-edge MRI
sequences will be added as well for quantifying lesion load per neuronal
pathway in both the brain and the spinal cord.

Methods for achieving SA1

:   Statistical data integration approaches will be used to explore the
    statistical association between IGP, clinical data and MRI data.
    These approaches are meant to integrate different heterogeneous data
    sources by separating the common and specific information they
    contain about the phenomenon under study.

Methods for achieving SA2

:   Clustering methods adapted for functional data will be used.
    Particular attention will be paid to semi-supervised approaches to
    account for clinical data and/or MRI data.

Methods for achieving SA3

:   Functional-on-functional regression models will be used for
    predicting lesion load from the IGP. Scalar-on-functional regression
    models and supervised classification methods will be used for
    predicting group membership from the IGP.

Chances are that none of the existing statistical approaches will be
straightforwardly applicable to deal with our IGP. This is because the
IGP is a functional data evaluating in the space of unit quaternion. As
a result, a key aspect for achieving our SAs will be to adapt existing
or create novel statistical methods that accommodate unit quaternion
time series.

# Expected Applications

The use of advanced cerebral and spinal MRI methods, not yet used in
clinical practice, allows one to quantify lesion load at the granularity
of the single neuronal pathway. We ambition:

-   to elaborate groupwise gait patterns (GGP) from the quantified
    lesion load obtained from the MRI data,
-   to facilitate the assessment of gait impairment for patients by
    matching his/her IGP to the closest GGP.

This work could have a significant impact since it could provide, during
the clinical exam, a specific assessment of gait impairment. This would
provide the neurologist with the means to propose dedicated follow-up at
early onset of walking deficiencies or even possibly before any
symptomatic discomfort. This would ultimately limit or delay aggravated
walking deficiencies, which is one of the main fears reported by MS
patients.

# Consortium

The scientific team behind the MS-CSI project is multidisciplinary and
can be divided into $4$ components, the member of which are listed in
the tables below.

| Name           | Qualification                     | Affiliation                 |
|----------------|-----------------------------------|-----------------------------|
| Aymeric STAMM  | Research Engineer in Statistics   | CNRS (LMJL)                 |
| Lise BELLANGER | Associate Professor in Statistics | Nantes Univ. (LMJL)         |
| Pierre DROUIN  | Ph.D. candidate (CIFRE)           | UmanIT, Nantes Univ. (LMJL) |

: Component 1: Statistical Modeling

+-----------------+--------------------------------+-------------------+
| Name            | Qualification                  | Affiliation       |
+=================+================================+===================+
| David-Axel      | Neurologist                    | University        |
| LAPLAUD         |                                | Hospital of       |
|                 |                                | Nantes            |
+-----------------+--------------------------------+-------------------+
| Pierre-Antoine  | Hospital practitioner in       | University        |
| GOURRAUD        | cellular biology               | Hospital of       |
|                 |                                | Nantes            |
+-----------------+--------------------------------+-------------------+
| Laetitia BARBIN | Translational project manager  | University        |
|                 |                                | Hospital of       |
|                 |                                | Nantes, CIC       |
|                 |                                | Neurologie        |
+-----------------+--------------------------------+-------------------+
| Mélinda MOYON   | Clinical study technician      | University        |
|                 |                                | Hospital of       |
|                 |                                | Nantes, CIC       |
|                 |                                | Neurologie        |
+-----------------+--------------------------------+-------------------+
| Alina GAULTIER  | Neuroradiologist               | University        |
|                 |                                | Hospital of       |
|                 |                                | Nantes            |
+-----------------+--------------------------------+-------------------+

: Component 2: Clinical study coordination, MRI acquisitions and
clinical expertise on MS

+-----------------+----------------+-----------------------------------+
| Name            | Qualification  | Affiliation                       |
+=================+================+===================================+
| Anne KERBRAT    | Neurologist    | University Hospital of Rennes,    |
|                 |                | INRIA Empenn                      |
+-----------------+----------------+-----------------------------------+
| Benoit COMBES   | Post-doctoral  | INRIA Empenn                      |
|                 | fellow         |                                   |
+-----------------+----------------+-----------------------------------+
| Elise BANNIER   | MRI physicist  | University Hospital of Rennes,    |
|                 |                | INRIA Empenn                      |
+-----------------+----------------+-----------------------------------+
| Jean-Christophe | Ne             | University Hospital of Rennes,    |
| FERRE           | uroradiologist | INRIA Empenn                      |
+-----------------+----------------+-----------------------------------+
| Gilles EDAN     | Neurologist    | University Hospital of Rennes     |
+-----------------+----------------+-----------------------------------+

: Component 3: MRI acquisitions and analysis

| Name              | Qualification           | Affiliation                 |
|-------------------|-------------------------|-----------------------------|
| Laurent CHEVREUIL | CEO                     | UmanIT                      |
| Fanny DOISTAU     | CEO e-health            | UmanIT                      |
| Vincent GRAILLOT  | R&D engineer            | UmanIT                      |
| Pierre DROUIN     | Ph.D. candidate (CIFRE) | UmanIT, Nantes Univ. (LMJL) |

: Component 4: Connected devices / Individual gait patterns

# Resources

-   [First mainstream report [in
    French]](ms-csi/2021-04-08-msr1/index.html)
