---
title: "Publications"
---

## Journal Papers

### 2020

1.  I. Lovato, A. Pini, **A. Stamm**, M. Taquet, S. Vantini (2020). *Multiscale null hypothesis testing for network-valued data: analysis of brain networks of patients with autism*, Journal of the Royal Statistical Society, Series C, in press.
2.  A. Bizzi, R. Pascuzzo, J. Blevins, M. Moscatelli, M. Grisoli, R. Lodi, F.M. Doniselli, G.Castelli, M. Cohen, **A. Stamm**, L. Schonberger, B.S. Appleby, P. Gambetti (2020). *Subtype diagnosis of sporadic Creutzfeldt-Jakob disease with diffusion MRI*, Annals of Neurology, in press.

### 2019

1.  I. Lovato, A. Pini, **A. Stamm**, S. Vantini (2019). *Model-free two-sample test for network-valued data*, Computational Statistics and Data Analysis, Vol. **144**, pp. 106896. DOI: [10.1016/j.csda.2019.106896](https://doi.org/10.1016/j.csda.2019.106896).

### 2018

1.  A. Agosti, C. Giverso, E. Faggiano, **A. Stamm**, P. Ciarletta (2018). *A personalized mathematical tool for neuro-oncology: a clinical case study*,,Journal of Non-Linear Mechanics, Special Issue on Multi-scale nonlinear continuum mechanical coupled field modelling and applications, Vol. **107**, pp. 170-81. DOI: [10.1016/j.ijnonlinmec.2018.06.004](https://doi.org/10.1016/j.ijnonlinmec.2018.06.004).
2.  A. Pini, **A. Stamm**, S. Vantini (2018). *Hotelling's* $T^2$ *in separable Hilbert spaces*,,Journal of Multivariate Analysis, Vol. **167**, pp. 284-305. DOI: [10.1016/j.jmva.2018.05.007](https://doi.org/10.1016/j.jmva.2018.05.007).
3.  C. Velasco-Annis, A. Akhondi-Asl, **A. Stamm**, S.K. Warfield (2018). *Reproducibility of Brain MRI Segmentation Algorithms: Empirical Comparison of Local MAP PSTAPLE, FreeSurfer, and FSL-FIRST*,,Journal of Neuroimaging, Vol. **22**(2), pp.162-72. DOI: [10.1111/jon.12483](https://doi.org/10.1111/jon.12483).

### 2017

1.  F. Baumer, J.M. Peters, S. Clancy, A.K. Prohl, S.P. Prabhu, B. Scherrer, F.E. Jansen, K.P.J. Braun, M. Sahin, **A. Stamm**, S.K. Warfield (2017). *Corpus callosum white matter diffusivity reflects cumulative neurological comorbidity in Tuberous Sclerosis Complex*, Cerebral Cortex, Vol. **28**(10), pp. 3665-72. DOI: [10.1093/cercor/bhx247](https://doi.org/10.1093/cercor/bhx247).

### 2016

1.  M.A. Breen, A. Tsai, **A. Stamm**, P.K. Kleinman (2016). *Bone age assessment practices in infants and older children among Society for Pediatric Radiology members*, Pediatric Radiology, Vol. **46**(9), pp. 1269-74. DOI: [10.1007/s00247-016-3618-7](https://doi.org/10.1007/s00247-016-3618-7).

### 2015

1.  J.M. Peters, A.K. Prohl, X. Tomas-Fernandez, M. Taquet, B. Scherrer, S.P. Prabhu, H.G. Lidov, J.M. Singh, F.E. Jansen, K.P.J. Braun, M. Sahin, S.K. Warfield, **A. Stamm** (2015). *Tubers are neither static nor discrete: Evidence from serial diffusion tensor imaging*, Neurology, Vol. **85**(18), pp. 1536-45. DOI: [10.1212/WNL.0000000000002055](https://doi.org/10.1212/WNL.0000000000002055).
2.  S. Pujol, W. Wells, C. Pierpaoli, C. Brun, J. Gee, G. Cheng, B. Vemuri, O. Commowick, S. Prima, **A. Stamm**, M. Goubran, A. Khan, T. Peters, P. Neher, K.H. Maier-Hein, Y. Shi, A. Tristan-Vega, G. Veni, R. Whitaker, M. Styner, C.F. Westin, S. Gouttard, I. Norton, L.Chauvin, H. Mamata, G. Gerig, A. Nabavi, A. Golby, R. Kikinis (2015). *The DTI Challenge: Toward Standardized Evaluation of Diffusion Tensor Imaging Tractography for Neurosurgery*,,Journal of Neuroimaging, Vol. **25**(6), pp. 875-82. DOI: [10.1111/jon.12283](https://doi.org/10.1111/jon.12283).

### 2013

1.  P. Secchi,**A. Stamm**, S. Vantini (2013). *Inference for the mean of large* $p$ *small* $n$ *data: a finite-sample high-dimensional generalization of Hotelling's theorem*, Electronic Journal of Statistics, Vol. **7**, pp. 2005-31. DOI: [10.1214/13-EJS833](https://doi.org/10.1214/13-EJS833).
2.  A. Esquevin, H. Raoult, J.C. Ferré, T. Ronzière, **A. Stamm**, M. Perennes, A. Bellou,,J.Y. Gauvrit (2013). *Systematic combined non-contrast CT-CT angiography in the management of unexplained non-traumatic coma*, The American Journal of Emergency Medicine, Vol. **31**(3), pp. 494-8. DOI: [10.1016/j.ajem.2012.09.024](https://doi.org/10.1016/j.ajem.2012.09.024).
3.  H. Raoult, F. Eugène, J.C. Ferré, J.C. Gentric, T. Ronzière, **A. Stamm**, J.Y. Gauvrit (2013). *Prognostic factors for outcomes after mechanical thrombectomy with solitaire stent*,,Journal of neuroradiology (Journal de neuroradiologie), Vol. **40**(4), pp. 252-9. DOI: [10.1016/j.neurad.2013.04.001](https://doi.org/10.1016/j.neurad.2013.04.001). Distinction: as of January 2017, one of the $5$ most cited papers published in the Journal of Neuroradiology.

### 2012

1.  H. Raoult, J.C. Ferré, J. Petr, E. Bannier, **A. Stamm**, C. Barillot, J.Y. Gauvrit (2012). *Functional arterial spin labeling: optimal sequence duration for motor activation mapping in clinical practice*,,Journal of magnetic resonance imaging, Vol. **36**(6), pp. 1435-44. DOI: [10.1002/jmri.23782](https://doi.org/10.1002/jmri.23782).

### 2011

1.  H. Raoult, J. Petr, E. Bannier, **A. Stamm**, J.Y. Gauvrit, C. Barillot, J.C. Ferré (2011). Arterial spin labeling for motor activation mapping at 3T with a 32-channel coil: reproducibility and spatial accuracy in comparison with BOLD fMRI, NeuroImage, Vol. **58**(1), pp. 157-67. DOI: [10.1016/j.neuroimage.2011.06.011](https://doi.org/10.1016/j.neuroimage.2011.06.011).

## Conference proceedings

### 2018

1.  **A. Stamm**, O. Commowick, A. Menafoglio, S. K. Warfield (2018). *A Bayes Hilbert space for compartment model computing in diffusion MRI*, in Proc. Medical Image Computing and Computer-Assisted Intervention -- MICCAI, Lecture Notes in Computer Science, Springer, Vol. **11072**, pp. 72-80, Granada (Spain). DOI: [10.1007/978-3-030-00931-1_9](https://doi.org/10.1007/978-3-030-00931-1_9).
2.  **A. Stamm**, A. Zito, V. Callioni, I. Sartori, L. Torriani, S. Vantini (2018). *Tractography-based atlas of the healthy cortico-spinal tract*, in Proc. International Society for Magnetic Resonance in Medicine - ISMRM, Vol. **26**, pp. 5202, Paris (France). URL: <http://indexsmart.mirasmart.com/ISMRM2018/PDFfiles/5202.html>.

### 2017

1.  A. Pini, **A. Stamm**, S. Vantini (2017). *Hotelling in Wonderland*, in Proc. International Workshop on Functional and Operatorial Statistics - IWFOS, Functional Statistics and Related Fields, Contributions to Statistics, Springer, pp. 211-6. A Coruña (Spain). DOI: [10.1007/978-3-319-55846-2_28](https://doi.org/10.1007/978-3-319-55846-2_28).

### 2016

1.  **A. Stamm**, O. Commowick, S.K. Warfield, S. Vantini (2016). *Comprehensive maximum likelihood estimation of diffusion compartment models towards reliable mapping of brain microstructure*, in Proc. Medical Image Computing and Computer-Assisted Intervention -- MICCAI, Lecture Notes in Computer Science, Springer, Vol. **9902**, pp. 622-30, Athens (Greece). DOI: [10.1007/978-3-319-46726-9_72](https://doi.org/10.1007/978-3-319-46726-9_72).
2.  O. Commowick, **A. Stamm**, S. Vantini, S.K. Warfield (2016). *Maximum likelihood estimators of brain white matter microstructure*, in Proc. 48*th* Scientific Meeting of the Italian Statistical Society - SIS, Salerno (Italy).

### 2015

1.  **A. Stamm**, J.M. Singh, O. Afacan, S.K. Warfield (2015). *Analytic quantification of bias and variance of coil sensitivity profile estimators for improved image reconstruction in MRI*, in Proc. Medical Image Computing and Computer-Assisted Intervention -- MICCAI, Lecture Notes in Computer Science, Springer, Vol. **9350**, pp. 684--91, Munchen (Germany). DOI: [10.1007/978-3-319-24571-3_82](https://doi.org/10.1007/978-3-319-24571-3_82).
2.  R. Hédouin, O. Commowick, **A. Stamm**, C. Barillot (2015). *Interpolation and averaging of multi-compartment model images*, in Proc. Medical Image Computing and Computer-Assisted Intervention -- MICCAI, Lecture Notes in Computer Science, Springer, Vol. **9349**, pp. 354-62, Munchen (Germany). DOI: [10.1007/978-3-319-24571-3_43](https://doi.org/10.1007/978-3-319-24571-3_43).
3.  A. Pini, **A. Stamm**, S. Vantini (2015). *Inference in functional Hilbert spaces generalizing the Hotelling's* $T^2$, in Proc. International Society for Non-Parametric Statistics - ISNPS, pp. 38, Graz (Austria).
4.  **A. Stamm**, O. Afacan, B. Scherrer, J.M. Singh, S.K. Warfield (2015). *In-vivo high resolution imaging of fine-scale anatomical structures at 3T with simultaneous bias-variance reduction*, in Proc. International Society for Magnetic Resonance in Medicine - ISMRM, Vol. **23**, pp. 2464, Toronto (Canada).
5.  **A. Stamm**, J.M. Singh, B. Scherrer, O. Afacan, S.K. Warfield (2015). *Multi-session complex averaging for high resolution high SNR 3T MR visualization of ex-vivo hippocampus & insula*, in Proc. SPIE Medical Imaging: Image Processing, Vol. **9413**, pp. 941328, Orlando (USA). DOI: [10.1117/12.2082493](https://doi.org/10.1117/12.2082493).
6.  B. Scherrer, O. Afacan, **A. Stamm**, J.M. Singh, S.K. Warfield (2015). *Optimized magnetic resonance diffusion protocol for ex-vivo whole human brain imaging with a clinical scanner*, in Proc. SPIE Medical Imaging: Physics of Medical Imaging, Vol. **9412**, pp. 94122U, Orlando (USA). DOI: [10.1117/12.2082387](https://doi.org/10.1117/12.2082387).

### 2014

1.  **A. Stamm**, O. Commowick, P. Pérez, C. Barillot (2014). *Fast identification of optimal fascicle configurations from standard clinical diffusion MRI using Akaike information criterion*, in Proc. 11th International Symposium on Biomedical Imaging - ISBI, IEEE, pp. 238--41, Beijing (China). DOI: [10.1109/ISBI.2014.6867853](https://doi.org/10.1109/ISBI.2014.6867853).
2.  **A. Stamm**, B. Scherrer, O. Commowick, C. Barillot, S.K. Warfield (2014). *Fast and robust detection of the optimal number of fascicles in diffusion images using model averaging theory*, in Proc. International Society for Magnetic Resonance in Medicine - ISMRM, Vol. **22**, pp. 2629, Milan (Italy).
3.  **A. Stamm**, B. Scherrer, S. Baraldo, O. Commowick, S.K. Warfield (2014). *Non-central chi estimation of multi-compartment models improves model selection by reducing overfitting*, in Proc. International Society for Magnetic Resonance in Medicine - ISMRM, Vol. **22**, pp. 2623, Milan (Italy).

### 2013

1.  **A. Stamm**, O. Commowick, C. Barillot, P. Pérez (2013). *Adaptive multi-modal particle filtering for probabilistic white matter tractography*, in Proc. Information Processing in Medical Imaging - IPMI, Springer, Vol. **7917**, pp. 594-606, Asilomar (USA). DOI: [10.1007/978-3-642-38868-2_50](https://doi.org/10.1007/978-3-642-38868-2_50).

### 2012

1.  O. Commowick, **A. Stamm** (2012). *Non-local robust detection of DTI white matter differences with small databases*, in Proc. Medical Image Computing and Computer-Assisted Intervention - MICCAI, Lecture Notes in Computer Science, Springer, Vol. **7512**, pp. 476-84, Nice (France). DOI: [10.1007/978-3-642-33454-2_59](https://doi.org/10.1007/978-3-642-33454-2_59).
2.  **A. Stamm**, P. Pérez, C. Barillot (2012). *A new multi-fiber model for low angular resolution diffusion MRI*, in Proc. 9th International Symposium on Biomedical Imaging - ISBI, IEEE, pp. 936--9, Barcelona (Spain). DOI: [10.1109/ISBI.2012.6235710](https://doi.org/10.1109/ISBI.2012.6235710).
3.  **A. Stamm**, P. Pérez, C. Barillot (2012). *A new multi-directional fiber model for low angular resolution diffusion imaging*, in Proc. International Society for Magnetic Resonance in Medicine - ISMRM, Vol. **20**, pp. 908, Melbourne (Australia).

### 2011

1.  P. Secchi, **A. Stamm**, S. Vantini (2011). *A generalization of Hotelling's theorem for large* $p$ *small* $n$ *data*, in Proc. Statistical Computation and Complex Systems - S.Co., Padua, (Italy).

### 2010

1.  P. Secchi, **A. Stamm**, S. Vantini (2010). *Large* $p$ *small* $n$*: inference for the mean*, in Proc. 45th Scientific Meeting of the Italian Statistical Society - SIS, Padua (Italy).

## Patents

## Invited talks
